# Generated by Django 5.2.11 on 2026-02-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this integration', max_length=255)),
                ('integration_type', models.CharField(choices=[('loops', 'Loops')], help_text='The provider type (e.g. loops)', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (API keys, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudienceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Per-audience overrides or custom fields for this integration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='audiences.audience')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_integrations', to='integrations.integration')),
            ],
            options={
                'unique_together': {('audience', 'integration')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='audiences.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='integration_status_4ace1f_idx'), models.Index(fields=['created_at'], name='integration_created_6943ba_idx')],
            },
        ),
    ]
