# Generated by Django 5.2.11 on 2026-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_smtp_integration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('loops', 'Loops'), ('ntfy', 'Ntfy'), ('smtp', 'Smtp')], help_text='The provider type (e.g. loops)', max_length=50),
        ),
    ]
