# Generated by Django 5.2.12 on 2026-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integration_integration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('loops', 'Loops'), ('ntfy', 'Ntfy'), ('smtp', 'Smtp'), ('mailchimp', 'Mailchimp')], help_text='The provider type (e.g. loops)', max_length=50),
        ),
    ]
