# Generated by Django 5.2.12 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='audience',
            name='allow_duplicates',
            field=models.BooleanField(default=True),
        ),
    ]
